Repository Bixal/move.mil, pull requests merged in 2018-03, with the labels that each got.

#5 Feature/4/local docker
  .env.docker.example
  .env.example
  .gitignore
  .lando.yml
  Makefile
  README.md
  composer.json
  console/config.yml
  console/defaults.yml
  console/sites/docker.yml
  docker-compose.yml
  mariadb-init/.gitkeep
  traefik.yml
  web/sites/default/settings.php
Labels: enhancement, in progress, review needed

#6 Feature 156192726 update site config in custom theme display settings
  composer.json
  composer.lock
  config/sync/block.block.move_mil_account_menu.yml
  config/sync/block.block.move_mil_branding.yml
  config/sync/block.block.move_mil_breadcrumbs.yml
  config/sync/block.block.move_mil_content.yml
  config/sync/block.block.move_mil_footer.yml
  config/sync/block.block.move_mil_help.yml
  config/sync/block.block.move_mil_local_actions.yml
  config/sync/block.block.move_mil_local_tasks.yml
  config/sync/block.block.move_mil_main_menu.yml
  config/sync/block.block.move_mil_messages.yml
  config/sync/block.block.move_mil_page_title.yml
  config/sync/block.block.move_mil_search.yml
  config/sync/block.block.move_mil_tools.yml
  config/sync/block.block.uswds_account_menu.yml
  config/sync/block.block.uswds_branding.yml
  config/sync/block.block.uswds_breadcrumbs.yml
  config/sync/block.block.uswds_content.yml
  config/sync/block.block.uswds_footer.yml
  config/sync/block.block.uswds_help.yml
  config/sync/block.block.uswds_local_actions.yml
  config/sync/block.block.uswds_local_tasks.yml
  config/sync/block.block.uswds_main_menu.yml
  config/sync/block.block.uswds_messages.yml
  config/sync/block.block.uswds_page_title.yml
  config/sync/block.block.uswds_powered.yml
  config/sync/block.block.uswds_search.yml
  config/sync/block.block.uswds_tools.yml
  config/sync/core.entity_view_display.media.audio.default.yml
  config/sync/core.extension.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/move_mil.settings.yml
  config/sync/system.site.yml
  config/sync/system.theme.yml
  web/themes/custom/move_mil/assets/img/move.png
Labels: enhancement, in progress, review needed

#11 Feature/8/circle ci
  .circleci/config.yml
  .circleci/config/behat.yml
  .circleci/config/phpunit.xml
  .gitlab-ci.yml
  .gitlab-ci/behat.yml
  .gitlab-ci/phpunit.xml
  .travis.yml
  RoboFile.php
  artifacts/behat/.gitkeep
  composer.json
  composer.lock
  setup.sh
  tests/behat.yml
  tests/features/bootstrap/FeatureContext.php
  tests/features/demo.feature
  web/modules/custom/demo_module/demo_module.info.yml
  web/modules/custom/demo_module/demo_module.services.yml
  web/modules/custom/demo_module/src/DemoModuleExampleService.php
  web/modules/custom/demo_module/tests/src/Unit/DemoModuleExampleServiceTest.php
Labels: enhancement, in progress, review needed

#19 [WIP]Add initial contribution guidelines
  CONTRIBUTING.md
  CONTRIBUTORS.md
  LICENSE.md
  README.md
Labels: enhancement, in progress

#26 Feature/updating testing procedure
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitlab-ci.yml
  CONTRIBUTING.md
Labels: enhancement, review needed

#27 Feature/156211092/create menus module
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Makefile
  web/modules/custom/custom_move_mil_menus/composer.json
  web/modules/custom/custom_move_mil_menus/config/install/system.menu.main_menu.yml
  web/modules/custom/custom_move_mil_menus/config/install/system.menu.moving_guide.yml
  web/modules/custom/custom_move_mil_menus/config/install/system.menu.resources.yml
  web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.info.yml
  web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
  web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.module
Labels: enhancement, review needed

#29 Feature 18 style our header to match live site
  config/sync/move_mil.settings.yml
  config/sync/system.site.yml
  web/themes/custom/move_mil/package-lock.json
  web/themes/custom/move_mil/package.json
  web/themes/custom/move_mil/sass/_variables.scss
  web/themes/custom/move_mil/sass/uswds.scss
  web/themes/custom/move_mil/scss/_variables.scss
  web/themes/custom/move_mil/scss/components/_archive-banner.scss
  web/themes/custom/move_mil/scss/components/_usa-header-extended.scss
  web/themes/custom/move_mil/scss/uswds.scss
  web/themes/custom/move_mil/templates/layout/page.html.twig
  web/themes/custom/move_mil/templates/system/block/block--system-branding-block.html.twig
  web/themes/custom/move_mil/ustranscom-logo.svg
Labels: enhancement, review needed

#35 Feature 33 theme global menu navigation
  config/sync/block.block.mainmenu.yml
  config/sync/block.block.move_mil_main_menu.yml
  config/sync/core.extension.yml
  config/sync/system.menu.main_menu.yml
  config/sync/system.menu.moving_guide.yml
  config/sync/system.menu.resources.yml
  web/themes/custom/move_mil/preprocess/block/block__system_menu_block__main_menu.preprocess.inc
  web/themes/custom/move_mil/preprocess/menu/menu__main_menu.preprocess.inc
  web/themes/custom/move_mil/scss/_variables.scss
  web/themes/custom/move_mil/scss/components/_usa-header-extended.scss
  web/themes/custom/move_mil/scss/components/_usa-nav.scss
  web/themes/custom/move_mil/scss/uswds.scss
  web/themes/custom/move_mil/templates/layout/page.html.twig
Labels: enhancement, review needed

#39 updating drupal core because of psa-2018-002
  .gitignore
  composer.lock
Labels: bug, in progress
