Repository Bixal/move.mil, pull requests merged in 2018-04, with the labels that each got.

#46 Feature 41 theme text w image paragraph
  composer.json
  composer.lock
  config/sync/core.entity_view_display.paragraph.text_with_image.default.yml
  config/sync/core.extension.yml
  config/sync/extlink.settings.yml
  web/themes/custom/move_mil/scss/01-atoms/_images.scss
  web/themes/custom/move_mil/scss/03-organisms/_archive-banner.scss
  web/themes/custom/move_mil/scss/03-organisms/_paragraph--text-with-image.scss
  web/themes/custom/move_mil/scss/03-organisms/_usa-header-extended.scss
  web/themes/custom/move_mil/scss/03-organisms/_usa-nav.scss
  web/themes/custom/move_mil/scss/uswds.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--text-with-image.html.twig
Labels: enhancement, hold, review needed

#50 Feature 47 theme pro tip pgraph
  web/themes/custom/move_mil/images/icon--pro-tip.svg
  web/themes/custom/move_mil/package.json
  web/themes/custom/move_mil/scss/03-organisms/_paragraph--pro-tip.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--pro-tip.html.twig
Labels: enhancement, review needed

#52 updated our classes to be more america(usa)
  web/themes/custom/move_mil/scss/03-organisms/_paragraph--text-with-image.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--text-with-image.html.twig
Labels: review needed

#63 Feature 54 theme tutorial step in tutorial content type
  config/sync/core.entity_view_display.node.tutorial.default.yml
  web/themes/custom/move_mil/config/javascript.js
  web/themes/custom/move_mil/images/icon--arrow-left.svg
  web/themes/custom/move_mil/images/icon--arrow-right.svg
  web/themes/custom/move_mil/images/icon--list.svg
  web/themes/custom/move_mil/js/slider.js
  web/themes/custom/move_mil/package-lock.json
  web/themes/custom/move_mil/package.json
  web/themes/custom/move_mil/scss/03-organisms/_move-mil--tutorial.scss
  web/themes/custom/move_mil/scss/uswds.scss
  web/themes/custom/move_mil/templates/content/node--tutorial.html.twig
Labels: review needed

#65 Update tutorial configuration
  config/sync/core.entity_form_display.node.tutorial.default.yml
  config/sync/core.entity_form_display.paragraph.pro_tip.default.yml
  config/sync/core.entity_view_display.node.tutorial.default.yml
  config/sync/core.entity_view_display.node.tutorial.teaser.yml
  config/sync/core.entity_view_display.paragraph.pro_tip.default.yml
  config/sync/field.field.node.tutorial.field_tutorial_intro.yml
  config/sync/field.field.paragraph.pro_tip.field_protip_alignment.yml
  config/sync/field.field.paragraph.pro_tip.field_protip_image.yml
  config/sync/field.field.paragraph.tutorial_slideshow_image.field_slideshow_caption.yml
  config/sync/field.field.paragraph.tutorial_slideshow_image.field_slideshow_description.yml
  config/sync/field.storage.node.field_tutorial_intro.yml
  config/sync/field.storage.paragraph.field_protip_alignment.yml
  config/sync/field.storage.paragraph.field_protip_image.yml
Labels: enhancement, needs review

#66 Feature/aws
  .ebextensions/efs-create.config
  .ebextensions/efs-mount.config
  .ebextensions/packages.config
  .gitignore
  composer.json
  composer.lock
Labels: enhancement

#69 Feature 156621182 update slideshow paragraph w/if-else protips
  Makefile
  composer.json
  composer.lock
  config/sync/core.extension.yml
  web/themes/custom/move_mil/package.json
  web/themes/custom/move_mil/scss/02-molecules/_paragraph--tutorial-slideshow.scss
  web/themes/custom/move_mil/scss/03-organisms/_move-mil--tutorial.scss
  web/themes/custom/move_mil/scss/uswds.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--pro-tip.html.twig
Labels: enhancement, needs review

#72 Set homepage and 404 page
  config/sync/core.entity_view_display.node.tutorial.teaser.yml
  config/sync/system.site.yml
Labels: enhancement, needs review

#75 Add image title and image subtitle to tabular paragraph
  config/sync/core.entity_form_display.paragraph.tabular_data.default.yml
  config/sync/core.entity_view_display.paragraph.tabular_data.default.yml
  config/sync/field.field.paragraph.tabular_data.field_table_image_subtitle.yml
  config/sync/field.field.paragraph.tabular_data.field_table_image_title.yml
  config/sync/field.storage.paragraph.field_table_image_subtitle.yml
  config/sync/field.storage.paragraph.field_table_image_title.yml
Labels: enhancement, needs review

#77 updated our protip alignment field, template, and styles partial
  web/themes/custom/move_mil/scss/02-molecules/_paragraph--pro-tip.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--pro-tip.html.twig
Labels: needs review

#78 Feature 156620768 update themeing txt w image align if else title
  web/themes/custom/move_mil/scss/01-atoms/_headings.scss
  web/themes/custom/move_mil/scss/02-molecules/_paragraph--text-with-image.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--text-with-image.html.twig
Labels: needs review

#83 Feature 156620426 update theme global footer
  web/themes/custom/move_mil/scss/01-atoms/_attr.scss
  web/themes/custom/move_mil/scss/03-organisms/_usa-footer-secondary_section.scss
  web/themes/custom/move_mil/scss/03-organisms/_usa-header-extended.scss
  web/themes/custom/move_mil/scss/03-organisms/_usa-nav.scss
  web/themes/custom/move_mil/templates/layout/page.html.twig
Labels: needs review

#82 Feature/jump links
  Makefile
  composer.json
  composer.lock
  config/sync/core.extension.yml
  web/themes/custom/move_mil/js/scrollFix.js
  web/themes/custom/move_mil/templates/system/paragraph/paragraph.html.twig
Labels: enhancement, needs review

#88 new styles dropdown for adding collumns to our WYSISYG editor
  config/sync/editor.editor.full_html.yml
  config/sync/filter.format.full_html.yml
Labels: needs review

#93 Feature 156705960 update customer service pgraph config
  config/sync/core.entity_form_display.paragraph.callout_accordion.default.yml
  config/sync/core.entity_form_display.paragraph.customer_service_box.default.yml
  config/sync/core.entity_view_display.paragraph.callout_accordion.default.yml
  config/sync/core.entity_view_display.paragraph.customer_service_box.default.yml
  config/sync/field.field.paragraph.callout_accordion.field_callout_content.yml
  config/sync/field.field.paragraph.callout_accordion.field_callout_title.yml
  config/sync/field.field.paragraph.customer_service_box.field_comm_fax.yml
  config/sync/field.field.paragraph.customer_service_box.field_dsn_fax.yml
  config/sync/field.field.paragraph.customer_service_box.field_other_details.yml
  config/sync/field.field.paragraph.customer_service_box.field_service_description.yml
  config/sync/field.storage.paragraph.field_callout_content.yml
  config/sync/field.storage.paragraph.field_callout_title.yml
  config/sync/field.storage.paragraph.field_comm_fax.yml
  config/sync/field.storage.paragraph.field_dsn_fax.yml
  config/sync/field.storage.paragraph.field_other_details.yml
  config/sync/field.storage.paragraph.field_service_description.yml
  config/sync/paragraphs.paragraphs_type.callout_accordion.yml
Labels: needs review

#97 Feature 156885931 include node class module
  composer.json
  composer.lock
  config/sync/core.extension.yml
  web/themes/custom/move_mil/scss/04-pages/_svc-two-col-content.scss
  web/themes/custom/move_mil/scss/uswds.scss
Labels: needs review

#98 Jump Links
  composer.lock
  config/sync/block.block.jumplinks.yml
  config/sync/block.block.move_mil_help.yml
  config/sync/block.block.move_mil_local_actions.yml
  config/sync/block.block.move_mil_local_tasks.yml
  config/sync/block.block.move_mil_page_title.yml
  config/sync/block.block.move_mil_tools.yml
  web/themes/custom/move_mil/scss/02-molecules/_jump-links.scss
  web/themes/custom/move_mil/scss/03-organisms/_block-jumplinks.scss
  web/themes/custom/move_mil/scss/_variables.scss
  web/themes/custom/move_mil/templates/system/block/block--jumplinks.html.twig
Labels: needs review

#114 updated some properties to use or variables
  web/themes/custom/move_mil/scss/04-pages/_page--front.scss
Labels: needs review

#119 updated styles and and template structure to set <button> and aria control to callout accordion by usa-accordion-content-pid
  web/themes/custom/move_mil/scss/02-molecules/_paragraph--callout-accordion.scss
  web/themes/custom/move_mil/templates/system/paragraph/paragraph--callout-accordion.html.twig
Labels: needs review

#121 Feature 156691172 clean views listing
  config/sync/views.view.comment.yml
  config/sync/views.view.comments_recent.yml
  config/sync/views.view.content_recent.yml
  config/sync/views.view.frontpage.yml
  config/sync/views.view.who_s_new.yml
  config/sync/views.view.who_s_online.yml
  web/themes/custom/move_mil/templates/content/node--tutorial.html.twig
Labels: needs review
